name: Build rpi kernel github action
on: [push]
jobs:
  build-rpi-kernel:
    runs-on: ubuntu-latest
    env:
      ARCH: arm64
      KERNEL: kernel8
      CONFIG_LOCALVERSION: "-v8l-custom"
      CROSS_COMPILE: aarch64-linux-gnu-
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: rpi-5.10.y
      - name: build kernel
        run: |
          sudo apt update && sudo apt install -y git bc bison flex libssl-dev make crossbuild-essential-arm64
          make bcm2711_defconfig
          make -j3 Image modules dtbs
          cp /usr/src/linux/arch/arm64/boot/dts/broadcom/*.dtb /target/boot/
          cp /usr/src/linux/arch/arm64/boot/dts/overlays/*.dtb* /target/boot/overlays/
          cp /usr/src/linux/arch/arm64/boot/dts/overlays/README /target/boot/overlays/
          cp /usr/src/linux/arch/arm64/boot/Image /target/boot/$KERNEL.img

      - name: Archive boot fs
        uses: actions/upload-artifact@v2
        with:
          name: boot
          path: /target/boot
